zuul:
  routes:
    app:
      path: /**
      url: http://localhost:8080

server:
  port: 8000
  use-forward-headers: true

logging:
  level:
    root: INFO

stormpath:
  zuul:
    account:
      header:
        jwt:
          key:
            resource: classpath:rsatest.priv.pem
            # this is just one example of a key id - anything that the origin server can make sense of to lookup
            # the corresponding public key is fine.  Here we use the public key file name (which the example origin app
            # has access to)
            id: rsatest.pub.pem
